### ISSUE TITLE
Szeto's To-Do-List

### ISSUE THREAD

**Issue by emceszeto** [githubteacher/dev-dec-19#24]
### To Do List

- [x] Create an issue
- [ ] Create a branch
- [ ] Make changes and push
- [ ] Create a PR
- [ ] Merge
- [ ] Have a good day
