### ISSUE TITLE
Herecomesjaycee's to-do list

### ISSUE THREAD

**Issue by herecomesjaycee** [githubteacher/dev-dec-19#33]
- [x] Create an issue
- [x] Create a branch
- [x] Make changes & push
- [x] Create a PR (pull request)
- [ ] Merge
- [x] Have a good time
